language: php
php:
  - '5.5'
  - '5.6'
  - hhvm
services:
  - mysql
install:
  - composer update
before_script:
  - mysql -e 'create database seat_test;'
  - mysql < tests/scripts/database.sql
  - mysql < tests/scripts/seeding.sql
script:
  - mkdir build/logs -p
  - php vendor/bin/phpunit -c phpunit.xml
after_success:
  - travis_retry php vendor/bin/coveralls -v
  - travis_retry php vendor/bin/test-reporter
  - travis_retry php vendor/bin/codacycoverage clover build/logs/clover.xml